/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.ABMAbuelo;

import Controlador.ControladorABMAbuelos.ControladorABMAbuelos;
import Controlador.DTO.DTOAbuelo;
import Controlador.DTO.DTOObraSocial;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Maxi
 */
public class RegistrarObraSocial extends javax.swing.JDialog {
public static DTOObraSocial dto;
    /**
     * Creates new form RegistrarObraSocial
     */
    public RegistrarObraSocial(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        dto = new DTOObraSocial();
        
    }
    
        public RegistrarObraSocial(java.awt.Frame parent, boolean modal,Long idAbuelo,ControladorABMAbuelos controlador) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        dto = new DTOObraSocial();
        DTOAbuelo dtoAbuelo = controlador.buscar(idAbuelo);
        dto = dtoAbuelo.getDTOobraSocial();
        textCredencialAfiliacion.setText(dto.getCredencialDeAfiliacion());
        textDisposicion.setText(dto.getDisposicionNro());
        textDomicilio.setText(dto.getDomicilio());
        textEmitidoPor.setText(dto.getEmitidoPor());
        textExpedienteNro.setText(dto.getExpedienteNro());
        textFechaAltaCredencial.setText(dto.getFechaAltaCredencial());
        textFechaEmisionCredencial.setText(dto.getFechaEmisionCredencial());
        textFechaVencimientoCredencial.setText(dto.getFechaVencimientoCredencial());
        textFechaVigenciaCredencial.setText(dto.getFechaVigenciaCredencial());
        textFechaVigenciaMedica.setText(dto.getFechaVigenciaMedico());
        textGP.setText(dto.getGp());
        textLocalidad.setText(dto.getLocalidad());
        textModuloInternacion.setText(dto.getModuloInternacion());
        textNombreObra.setText(dto.getNombreObraSocial());
        textNombremedico.setText(dto.getNombremedicoCabecera());
        textNroModulo.setText(dto.getNroModulo());
        textNumeroBeneficio.setText(dto.getNumeroBeneficio());
        textNumeroMedico.setText(dto.getNumeroMedicoCabecera());
        textfechaVigenciaModulo.setText(dto.getFechaVigenciaModulo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textNombreObra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textCredencialAfiliacion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textFechaEmisionCredencial = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textFechaVigenciaCredencial = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textFechaAltaCredencial = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textFechaVencimientoCredencial = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textNumeroBeneficio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        textGP = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        textEmitidoPor = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        textExpedienteNro = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        textDisposicion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        textDomicilio = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        textLocalidad = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        textNombremedico = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        textNumeroMedico = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        textFechaVigenciaMedica = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        textModuloInternacion = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        textNroModulo = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        textfechaVigenciaModulo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar Obra Social");

        jLabel2.setText("Nombre Obra social:");

        jLabel3.setText("Credencial de afiliacion:");

        jLabel4.setText("Fecha de emision de credencial:");

        jLabel5.setText("Rellene los siguientes campos: (Nota: Las fechas se deben ingresar del siguiente formato dd/MM/yyyy)");

        jLabel6.setText("Fecha de vigencia de credencial:");

        jLabel7.setText("Fecha Alta credencial:");

        jLabel8.setText("Fecha de vencimiento de credencial:");

        jLabel9.setText("Numero de beneficio:");

        jLabel10.setText("GP:");

        jLabel11.setText("Emitido por:");

        textEmitidoPor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEmitidoPorActionPerformed(evt);
            }
        });

        jLabel12.setText("Expediente Nro:");

        jLabel13.setText("Disposicion Nro:");

        jLabel14.setText("Domicilio:");

        jLabel15.setText("Localidad:");

        jLabel16.setText("Nombre medico de cabecera:");

        jLabel17.setText("Numero medico:");

        jLabel18.setText("Fecha vigencia medica:");

        jLabel19.setText("Modulo de internacion:");

        jLabel20.setText("Nro modulo:");

        textNroModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNroModuloActionPerformed(evt);
            }
        });

        jLabel21.setText("Fecha de vigencia del modulo:");

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(textEmitidoPor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                                .addComponent(textNombremedico, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textNumeroMedico, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textFechaVigenciaMedica, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(textExpedienteNro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(textNombreObra, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textCredencialAfiliacion, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFechaEmisionCredencial, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFechaVigenciaCredencial, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFechaAltaCredencial, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFechaVencimientoCredencial, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textNumeroBeneficio, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textDomicilio, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textGP, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel13))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textDisposicion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton1))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel21))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textModuloInternacion, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textNroModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textfechaVigenciaModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textNombreObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textCredencialAfiliacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textFechaEmisionCredencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textFechaVigenciaCredencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textFechaAltaCredencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(textFechaVencimientoCredencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(textNumeroBeneficio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textGP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(textEmitidoPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textExpedienteNro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)
                        .addComponent(textDisposicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(textDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(textLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(textNombremedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(textNumeroMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(textFechaVigenciaMedica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(textModuloInternacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(textNroModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(textfechaVigenciaModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNroModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNroModuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNroModuloActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        dto.setCredencialDeAfiliacion(textCredencialAfiliacion.getText());
        dto.setDisposicionNro(textDisposicion.getText());
        dto.setDomicilio(textDomicilio.getText());
        dto.setEmitidoPor(textEmitidoPor.getText());
        dto.setExpedienteNro(textExpedienteNro.getText());    

        
 
 
        dto.setFechaAltaCredencial(textFechaAltaCredencial.getText());
        dto.setFechaEmisionCredencial(textFechaEmisionCredencial.getText());
        dto.setFechaVencimientoCredencial(textFechaVencimientoCredencial.getText());
        dto.setFechaVigenciaCredencial(textFechaVigenciaCredencial.getText());
        dto.setFechaVigenciaMedico(textFechaVigenciaMedica.getText());
        dto.setFechaVigenciaModulo(textfechaVigenciaModulo.getText());
            
      

        
        dto.setGp(textGP.getText());
        dto.setLocalidad(textLocalidad.getText());
        dto.setModuloInternacion(textModuloInternacion.getText());
        dto.setNombreObraSocial(textNombreObra.getText());
        dto.setNombremedicoCabecera(textNombremedico.getText());
        dto.setNroModulo(textNroModulo.getText());
        dto.setNumeroBeneficio(textNumeroBeneficio.getText());
        dto.setNumeroMedicoCabecera(textNumeroMedico.getText());
        
        this.dispose();
    
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textEmitidoPorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEmitidoPorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEmitidoPorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarObraSocial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarObraSocial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarObraSocial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarObraSocial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegistrarObraSocial dialog = new RegistrarObraSocial(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField textCredencialAfiliacion;
    private javax.swing.JTextField textDisposicion;
    private javax.swing.JTextField textDomicilio;
    private javax.swing.JTextField textEmitidoPor;
    private javax.swing.JTextField textExpedienteNro;
    private javax.swing.JTextField textFechaAltaCredencial;
    private javax.swing.JTextField textFechaEmisionCredencial;
    private javax.swing.JTextField textFechaVencimientoCredencial;
    private javax.swing.JTextField textFechaVigenciaCredencial;
    private javax.swing.JTextField textFechaVigenciaMedica;
    private javax.swing.JTextField textGP;
    private javax.swing.JTextField textLocalidad;
    private javax.swing.JTextField textModuloInternacion;
    private javax.swing.JTextField textNombreObra;
    private javax.swing.JTextField textNombremedico;
    private javax.swing.JTextField textNroModulo;
    private javax.swing.JTextField textNumeroBeneficio;
    private javax.swing.JTextField textNumeroMedico;
    private javax.swing.JTextField textfechaVigenciaModulo;
    // End of variables declaration//GEN-END:variables
}
